default: &default
  DB_HOST: "db"
  DB_PORT: "5432"
  USERNAME: "postgres"
  MAILER_DEFAULT_HOST: "localhost"
  MAILER_DEFAULT_PORT: "3000"
  MAILER_SENDER: "Test <noreply@nimbl3.co>"

development:
  <<: *default
  DB_NAME: "#{app_name}_development"
  SECRET_KEY_BASE: "#{secret_key_base}"

test:
  <<: *default
  DB_NAME: "#{app_name}_test"
  TEST_RETRY: "0"
  SECRET_KEY_BASE: "#{secret_key_base}"
